env:
  global:
    - VERSION=0.${TRAVIS_BUILD_NUMBER}
    - DOCKER_HUB_USER=vfarcic

sudo: required

services:
  - docker

script:
  - set -e
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -v go:/go golang:1.6 bash -c "go get -t github.com/stretchr/testify/suite && go get -d -v -t && go test --cover ./... --run UnitTest && CGO_ENABLED=0 GOOS=linux go build -v -o docker-flow-monitor"
  - docker build -t vfarcic/docker-flow-monitor .
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag vfarcic/docker-flow-monitor vfarcic/docker-flow-monitor:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-monitor:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-monitor; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker run -t -v $PWD:/docs cilerler/mkdocs bash -c "pip install pygments && pip install pymdown-extensions && mkdocs build"; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t vfarcic/docker-flow-monitor-docs -f Dockerfile.docs .; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag vfarcic/docker-flow-monitor-docs vfarcic/docker-flow-monitor-docs:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-monitor-docs:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-monitor-docs; fi'

branches:
  only:
    - master
