version: "3"

services:

  monitor:
    image: vfarcic/docker-flow-monitor:${TAG:-latest}
    networks:
      - proxy
      - monitor
    ports:
      - 9090:9090
    environment:
      - ARG_WEB_EXTERNAL-URL=http://prometheus.dockerflow.com
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=prometheus.dockerflow.com
        - com.df.port=9090
        - com.df.usersPassEncrypted=true
        - com.df.usersSecret=vfarcic

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/reconfigure
    deploy:
      placement:
        constraints: [node.role == manager]

  docs:
    image: vfarcic/docker-flow-monitor-docs:${TAG:-latest}
    networks:
      - proxy
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.serviceDomain=monitor.dockerflow.com
        - com.df.servicePath=/
      replicas: 2
      resources:
        reservations:
          memory: 50M

networks:
  monitor:
    external: true
  proxy:
    external: true
